# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/thyoo/vivado/tft_lcd_practice/tft_lcd_practice.srcs/sources_1/ip/bufferram/bufferram.xci
# IP: The module: 'bufferram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thyoo/vivado/tft_lcd_practice/tft_lcd_practice.srcs/sources_1/ip/bufferram/bufferram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bufferram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/thyoo/vivado/tft_lcd_practice/tft_lcd_practice.srcs/sources_1/ip/bufferram/bufferram.xci
# IP: The module: 'bufferram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thyoo/vivado/tft_lcd_practice/tft_lcd_practice.srcs/sources_1/ip/bufferram/bufferram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bufferram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
