# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src_ps_testlcd/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_2 || ORIG_REF_NAME==system_processing_system7_0_2} -quiet] -quiet

# IP: bd/system/ip/system_textlcd_0_2/system_textlcd_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_textlcd_0_2 || ORIG_REF_NAME==system_textlcd_0_2} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_2/system_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_2 || ORIG_REF_NAME==system_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_2 || ORIG_REF_NAME==system_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
